#!/bin/sh
# make default editor Neovim
export EDITOR=nvim

export XDG_SESSION_TYPE=wayland
export XCURSOR_SIZE=12
export GDK_SCALE=1.5

# Most pure GTK3 apps use wayland by default, but some,
# like Firefox, need the backend to be explicitely selected.
export MOZ_ENABLE_WAYLAND=1
export MOZ_DBUS_REMOTE=1
export GTK_CSD=0

# qt wayland
export QT_QPA_PLATFORM="wayland"
export QT_QPA_PLATFORMTHEME=gtk2
export QT_WAYLAND_DISABLE_WINDOWDECORATION="1"
export QT_STYLE_OVERRIDE=kvantum

export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
export QT_WAYLAND_FORCE_DPI=144

#Java XWayland blank screens fix
export _JAVA_AWT_WM_NONREPARENTING=1

# set default shell and terminal
export SHELL=/usr/bin/zsh
export TERMINAL_COMMAND=kitty

# add default location for zeit.db
export ZEIT_DB="$HOME/config/zeit.db"

# Disable hardware cursors. This might fix issues with
# disappearing cursors
if systemd-detect-virt -q; then
    # if the system is running inside a virtual machine, disable hardware cursors
    export WLR_NO_HARDWARE_CURSORS=1
fi

set -a
. "$HOME/.config/user-dirs.dirs"
set +a

if [ -n "$(ls "$HOME"/.config/profile.d 2>/dev/null)" ]; then
    for f in "$HOME"/.config/profile.d/*; do
        # shellcheck source=/dev/null
        . "$f"
    done
fi

export GTK_THEME="Tokyo-Night"
